# permissions for end users to edit canaries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: canary-editor-role
rules:
- apiGroups:
  - cd.org.smart
  resources:
  - canaries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cd.org.smart
  resources:
  - canaries/status
  verbs:
  - get
