apiVersion: cd.org.smart/v1alpha1
kind: Canary
metadata:
  namespace: canary-sample
  name: my-nginx-app
spec:
  rollout:
    minReadySeconds: 30
    strategy:
      maxSurge: "25%"
      maxUnavailable: 0
      Weight: 20
  deployment:
    replicas: 4
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
              - containerPort: 80