apiVersion: cd.org.smart/v1alpha1
kind: Canary
metadata:
  namespace: canary-sample
  name: my-nginx-app
spec:
  deployment:
    replicas: 3
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
              - containerPort: 80