apiVersion: cd.org.smart/v1alpha1
kind: Canary
metadata:
  namespace: canary-sample
  name: my-nginx-app
spec:
  strategy:
    podWeight: "0.25"
    traffic:
      type: istio # nginx istio traefik
      weight: "0.25"
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: 0
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80